<a href="https://colab.research.google.com/github/JakeOh/202011_itw_bd21/blob/main/lab_da/da02_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# np.ndarray 객체 생성 함수들

In [1]:
import numpy as np

**`np.array(array-like object)` 함수**

*   array-like object: list, tuple, ndarray


In [2]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [5]:
arr = np.array([2 * x for x in range(5)])
print(arr)

[0 2 4 6 8]


**`np.arange(start, end, step)` 함수**

*   array using range.
*   1-d array를 생성.
*   range(end), range(start, end), range(start, end, step)


In [8]:
print(np.arange(5))
print(np.arange(1, 6))
print(np.arange(0, 10, 2))

[0 1 2 3 4]
[1 2 3 4 5]
[0 2 4 6 8]


**`ndarray.reshape(shape)` 메서드**

*   `ndarray.reshape(tuple)`
*   `ndarray.reshape(x, y, ...)`

In [11]:
arr_1d = np.arange(6)
print(arr_1d)

arr_2d = arr_1d.reshape((2, 3))  # arr_1d.reshape(2, 3)
print(arr_2d)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [13]:
print(np.arange(6).reshape((3, 2)))

[[0 1]
 [2 3]
 [4 5]]


**`np.zeros(shape)` 함수**

*   모든 원소가 0인 ndarray를 생성


In [14]:
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
arr.dtype

dtype('float64')

In [18]:
print(np.zeros((2, 3), dtype=int))

[[0 0 0]
 [0 0 0]]


In [16]:
print(np.zeros(2, 3))
#> TypeError 발생

TypeError: ignored

**`np.ones(shape)` 함수**

*   모든 원소가 1로 이루어진 ndarray를 생성.


In [21]:
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


**`np.eye()` 함수**

*   대각선에는 1, 그 이외에는 0으로 채워진 2-d ndarray를 생성.


In [22]:
arr = np.eye(3, dtype=int)
print(arr)  #> (3, 3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [23]:
print(np.eye(3, 4, dtype=int))  #> (3, 4)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [24]:
print(np.eye(4, k=1, dtype=int))  #> (4, 4), 인덱스 1번 컬럼에서부터 대각선 생성.

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]
