<a href="https://colab.research.google.com/github/JakeOh/202011_itw_bd21/blob/main/lab_da/da02_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# np.ndarray 객체 생성 함수들

In [1]:
import numpy as np

**`np.array(array-like object)` 함수**

*   array-like object: list, tuple, ndarray


In [2]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [3]:
arr = np.array([2 * x for x in range(5)])
print(arr)

[0 2 4 6 8]


**`np.arange(start, end, step)` 함수**

*   array using range.
*   1-d array를 생성.
*   range(end), range(start, end), range(start, end, step)


In [4]:
print(np.arange(5))
print(np.arange(1, 6))
print(np.arange(0, 10, 2))

[0 1 2 3 4]
[1 2 3 4 5]
[0 2 4 6 8]


**`ndarray.reshape(shape)` 메서드**

*   `ndarray.reshape(tuple)`
*   `ndarray.reshape(x, y, ...)`

In [5]:
arr_1d = np.arange(6)
print(arr_1d)

arr_2d = arr_1d.reshape((2, 3))  # arr_1d.reshape(2, 3)
print(arr_2d)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [6]:
print(np.arange(6).reshape((3, 2)))

[[0 1]
 [2 3]
 [4 5]]


**`np.zeros(shape)` 함수**

*   모든 원소가 0인 ndarray를 생성


In [7]:
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
arr.dtype

dtype('float64')

In [9]:
print(np.zeros((2, 3), dtype=int))

[[0 0 0]
 [0 0 0]]


In [10]:
print(np.zeros(2, 3))
#> TypeError 발생

TypeError: ignored

**`np.ones(shape)` 함수**

*   모든 원소가 1로 이루어진 ndarray를 생성.


In [11]:
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


**`np.eye()` 함수**

*   대각선에는 1, 그 이외에는 0으로 채워진 2-d ndarray를 생성.


In [12]:
arr = np.eye(3, dtype=int)
print(arr)  #> (3, 3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [13]:
print(np.eye(3, 4, dtype=int))  #> (3, 4)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [14]:
print(np.eye(4, k=1, dtype=int))  #> (4, 4), 인덱스 1번 컬럼에서부터 대각선 생성.

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


**`np.random.rand(d0, d1, ...)` 함수**: 

0 <= r < 1 난수들로 이루어진 ndarray를 생성


In [15]:
arr = np.random.rand(5)
print(arr)

[0.50538968 0.10808349 0.24029363 0.31242837 0.40038432]


In [16]:
arr = np.random.rand(3, 2)
print(arr)

[[0.40626772 0.55659527]
 [0.84233542 0.03684263]
 [0.23624793 0.09092811]]


**`np.random.randn(d0, d1, ..., dn)` 함수**: 

평균이 0이고, 표준편차가 1인 표준정규분포(standard normal distribution)를 따르는 난수들의 배열을 생성.

In [19]:
arr = np.random.randn(10)
print(arr)

[ 1.32232687  0.51187603 -1.06279873  0.19425842  1.73546691  1.37107731
  0.47288974 -1.03607895  1.52916943  1.10309286]


In [20]:
arr = np.random.randn(4, 3)
print(arr)

[[-0.05805151  0.43101269 -0.33286644]
 [ 1.39153698  1.15177327  0.79829169]
 [ 1.29921611  0.49708884  2.05996418]
 [ 0.68684524  0.25330925  0.76983063]]


**`np.random.randint(low, high, size, dtype)` 함수**

*   low <= r < high 범위의 정수 난수들로 이루어진 배열을 생성.
*   size 파라미터에는 ndarray의 **shape**을 argument로 전달해야 함.

In [21]:
arr = np.random.randint(1, 4, size=10)
print(arr)

[2 3 3 1 2 3 2 2 1 2]


In [22]:
arr = np.random.randint(1, 4, size=(3, 4))
print(arr)

[[2 1 3 3]
 [3 1 1 1]
 [2 1 1 2]]
