<a href="https://colab.research.google.com/github/JakeOh/202011_itw_bd21/blob/main/lab_da/da03_numpy_index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [8]:
# Python의 list
array = [x for x in range(1, 11)]
print(array)
print(array[0])
print(array[-1])
print(array[1:5])  # slicing
print(array[:5])
print(array[5:])
print(array[-3:])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
1
10
[2, 3, 4, 5]
[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[8, 9, 10]


In [16]:
# numpy.ndarray
array = np.arange(1, 11)
print(array)
print(array[0])
print(array[9], array[-1])
print(array[1:5])  # slicing
print(array[:3])  # slicing할 때 시작 인덱스를 생략하면 첫번째 원소(인덱스 0번 원소)부터
print(array[7:])  # slicing할 때 끝 인덱스를 생략하면 마지막 원소까지
print(array[-3:])

[ 1  2  3  4  5  6  7  8  9 10]
1
10 10
[2 3 4 5]
[1 2 3]
[ 8  9 10]
[ 8  9 10]
