<a href="https://colab.research.google.com/github/JakeOh/202011_itw_bd21/blob/main/lab_da/da03_numpy_index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [8]:
# Python의 list
array = [x for x in range(1, 11)]
print(array)
print(array[0])
print(array[-1])
print(array[1:5])  # slicing
print(array[:5])
print(array[5:])
print(array[-3:])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
1
10
[2, 3, 4, 5]
[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[8, 9, 10]


In [16]:
# numpy.ndarray
array = np.arange(1, 11)
print(array)
print(array[0])
print(array[9], array[-1])
print(array[1:5])  # slicing
print(array[:3])  # slicing할 때 시작 인덱스를 생략하면 첫번째 원소(인덱스 0번 원소)부터
print(array[7:])  # slicing할 때 끝 인덱스를 생략하면 마지막 원소까지
print(array[-3:])

[ 1  2  3  4  5  6  7  8  9 10]
1
10 10
[2 3 4 5]
[1 2 3]
[ 8  9 10]
[ 8  9 10]


**fancy indexing**

배열과 비슷한 객체(array-like object: ndarray, list, tuple, ...)를 사용한 indexing 방법.

In [21]:
array = np.arange(1, 11)
print(array)
print(array[[0, 2, 4]])
print(array[[0, 1, 8, 9]])

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5]
[ 1  2  9 10]


**boolean indexing**

*   논릿값(True, False)들의 리스트(튜플, 배열 등)을 사용한 indexing 방법
*   numpy.ndarray의 원소들 중에서 조건을 만족하는 원소들로 이루어진 부분 집합 배열을 찾을 때 사용할 수 있음

In [24]:
array = np.array([1, 10, 100, 99, 88])
print(array)

indexer = [True, False, True, False, True]
print(indexer)

print(array[indexer])

[  1  10 100  99  88]
[True, False, True, False, True]
[  1 100  88]


In [29]:
# 0 이상 10 미만의 정수 난수 10개를 갖는 1-d ndarray를 생성
np.random.seed(1)
array = np.random.randint(0, 10, size=10)
print(array)

# array에서 짝수들만 선택
print(array % 2 == 0)  #> 1-d ndarray
print(array[array % 2 == 0])  #> boolean indexing

# array에서 홀수들만 선택
print(array[array % 2 == 1])

[5 8 9 5 0 0 1 7 6 9]
[False  True False False  True  True False False  True False]
[8 0 0 6]
[5 9 5 1 7 9]


*   boolean indexing에서는 Python의 논리 연산자(and, or, not)을 사용할 수 없음!
*   boolean indexing에서는 &, |, ~ 연산자를 사용함.
*   boolean indexing에서 &, |, ~ 연산자를 사용할 때는 연산 순서를 명시하기 위해서 *반드시* ()를 사용해야 함.

In [37]:
# 0 이상 20 미만의 정수 난수 10개를 갖는 1-d ndarray를 생성
np.random.seed(42)
array = np.random.randint(0, 20, size=10)
print(array)

# array의 원소들 중에서 5 이상 15 미만의 숫자들로 이루어진 배열
print(array[(array >= 5) & (array < 15)])

# array의 원소들 중에서 5 미만 또는 15 이상인 숫자들로 이루어진 배열
print(array[(array < 5) | (array >= 15)])

[ 6 19 14 10  7  6 18 10 10  3]
[ 6 14 10  7  6 10 10]
[19 18  3]


Python 2차원 list vs NumPy 2-d ndarray

*   `list[i][j]`
*   `array[i][j]`, `array[i, j]` 둘 다 가능