<a href="https://colab.research.google.com/github/JakeOh/202011_itw_bd21/blob/main/lab_da/da23_numpy_advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
a = np.ones((3, 4))  # dtype의 기본값은 np.float64(64 bits에 저장되는 실수 타입)
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
a = np.ones((3, 4), dtype=np.int_)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

*   ndarray의 속성(attribute)

In [5]:
a.dtype  # dtype: 배열이 저장하고 있는 원소들의 데이터 타입

dtype('int64')

In [6]:
a.shape  # shape: Tuple of array dimensions.
# 배열의 각 축(axis)를 따라서 있는 원소의 개수들의 tuple

(3, 4)

In [7]:
a.ndim  # dim: 배열의 축(axis)의 개수

2

In [8]:
a.strides  # strides: 보폭. 배열의 각 축을 따라서 다음 원소를 찾아가기 위해서 몇 bytes를 이동해야 하는지.

(32, 8)

In [9]:
a = np.arange(5, dtype=np.int16)  # 16 bits(2 bytes) 정수 5개를 저장하고 있는 1d 배열
a

array([0, 1, 2, 3, 4], dtype=int16)

In [10]:
a.ndim

1

In [11]:
a.shape

(5,)

In [12]:
a.strides

(2,)

In [13]:
# 3차원 ndarray
a = np.ones((2, 3, 4), dtype=np.int16)
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [14]:
a.ndim

3

In [15]:
a.shape

(2, 3, 4)

In [16]:
a.strides  # (3*4*2bytes, 4*2bytes, 2bytes)

(24, 8, 2)

*   ndarray 모양 변형(reshape)
    *   `reshape()`
    *   `ravel()`
    *   `flatten()`
    *   `np.newaxis`

In [19]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
a = np.arange(12).reshape((3, 4))  # 1d 배열을 (3, 4) shape의 2d 배열로 변환
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
a = np.arange(24).reshape((2, 3, 4))  # 1d 배열을 (2, 3, 4) shape의 2d 배열로 변환
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
a = np.arange(6).reshape((3, -1))  # 1d 배열을 row가 3개인 2d 배열로 변환. column 개수는 자동 계산.
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [24]:
a = np.arange(12).reshape((3, -1))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [28]:
a.reshape((-1, 3))  # 1d 배열을 column이 3개인 2d 배열로 변환. row 개수는 자동 계산

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [30]:
a.reshape((-1, 3, 4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [31]:
a.reshape((3, 4, -1))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [34]:
# np.ndarray.reshape(shape) 메서드
# np.reshape(array, shape) 함수
np.reshape(a, (4, -1))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

* 2d 배열을 1d 배열로 변환

In [35]:
a = np.arange(12).reshape((3, 4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
np.reshape(a, (12,))  # np.reshape(a, 12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
a.reshape((12,))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
np.ravel(a)  # 함수

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
a.ravel()  # 메서드

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
a.flatten()  # 메서드. np.flatten() 함수는 없음!

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
a.flatten()[0:12]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
# np.ndarray.flat 속성(attribute): 1차원으로 펼쳐진 배열을 저장하는 객체
a.flat

In [44]:
a.flat[0]

0

In [45]:
a.flat[-1]

11

In [46]:
a.flat[:]  # 배열 slicing

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a = np.arange(24).reshape((2, 3, 4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [54]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [56]:
a.reshape((2*3*4,))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])