<a href="https://colab.research.google.com/github/JakeOh/202011_itw_bd21/blob/main/lab_ml/ml15_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Perceptron

In [2]:
x = np.array([1, 2])
w = np.array([0.1, 0.2])

In [3]:
x * w

array([0.1, 0.4])

In [4]:
np.sum(x * w)

0.5

In [5]:
np.dot(x, w)

0.5

In [6]:
x.dot(w)

0.5

In [7]:
x @ w

0.5

## AND Gate

| $x_1$ | $x_2$ | $y$ |
|---|---|---|
| 0 | 0 | 0 |
| 0 | 1 | 0 |
| 1 | 0 | 0 |
| 1 | 1 | 1 |

In [14]:
def and_gate(x1, x2):
    w1, w2, th = 0.5, 0.5, 0.7
    result = x1 * w1 + x2 * w2
    if result > th:
        y = 1
    else:
        y = 0

    return y

In [15]:
and_gate(x1=0, x2=0)

0

In [16]:
and_gate(x1=0, x2=1)

0

In [17]:
and_gate(x1=1, x2=0)

0

In [18]:
and_gate(x1=1, x2=1)

1

In [19]:
def and_gate2(x1, x2):
    w1, w2, th = 0.1, 0.1, 0.1
    result = x1 * w1 + x2 * w2
    y = 1 if result > th else 0
    return y

In [23]:
and_gate2(1, 1)

1

AND 게이트를 만들 수 있는 가중치(w1, w2), 임계값(threshold)은 무수히 많은 조합이 있을 수 있음.

In [30]:
def and_gate3(x):
    """x는 원소가 2개인 1차원 배열. AND 논리 연산의 결과를 리턴."""
    w = np.array([0.5, 0.5])
    th = 0.7
    # y = 1 if np.sum(x * w) > th else 0
    y = 1 if np.dot(x, w) > th else 0
    return y

In [31]:
and_gate3(np.array([1, 1]))

1

In [39]:
def and_gate4(X):
    """X는 컬럼이 2개인 2차원 배열. 즉 shape은 (-1, 2). AND 논리 연산 결과를 리턴"""
    w = np.array([0.5, 0.5])  # 가중치(weight)
    th = 0.7
    y = (np.dot(X, w) > th).astype(np.int_)
    return y

In [33]:
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

In [40]:
and_gate4(X)

array([0, 0, 0, 1])

In [46]:
def and_gate5(X):
    w = np.array([0.5, 0.5])  # 가중치(weight)
    b = -0.7  # 편향(bias)
    result = np.dot(X, w) + b  # linear equation
    y = result > 0
    return y.astype(np.int_)

In [47]:
and_gate5(X)

array([0, 0, 0, 1])

In [48]:
def and_gate6(X):
    w_bias = np.array([-0.7, 0.5, 0.5])  # bias를 포함한 weights: (bias, w1, w2)
    n = len(X)
    X_bias = np.c_[np.ones(n), X]  # bias에는 1이 곱해짐.
    result = np.dot(X_bias, w_bias)  # X_bias @ w_bias
    y = result > 0
    return y.astype(np.int_)

In [49]:
and_gate6(X)

array([0, 0, 0, 1])

## NAND Gate

| $x_1$ | $x_2$ | $y$ |
|---|---|---|
| 0 | 0 | 1 |
| 0 | 1 | 1 |
| 1 | 0 | 1 |
| 1 | 1 | 0 |

In [50]:
def nand_gate(X):
    w_bias = np.array([-0.7, 0.5, 0.5])  # (b, w1, w2)
    n = len(X)
    X_bias = np.c_[np.ones(n), X]
    result = np.dot(X_bias, w_bias)
    y = result <= 0
    return y.astype(np.int_)

In [54]:
nand_gate(X)

array([1, 1, 1, 0])

## OR Gate

| $x_1$ | $x_2$ | $y$ |
|---|---|---|
| 0 | 0 | 0 |
| 0 | 1 | 1 |
| 1 | 0 | 1 |
| 1 | 1 | 1 |

In [57]:
def or_gate(X):
    w_bias = np.array([-0.5, 1, 1])
    n = len(X)
    X_bias = np.c_[np.ones(n), X]
    y = np.dot(X_bias, w_bias) > 0
    return y.astype(np.int_)

In [58]:
or_gate(X)

array([0, 1, 1, 1])

## XOR(Exclusive OR) Gate

| $x_1$ | $x_2$ | NAND($y_1$) | OR($y_2$) | z($y_1$ AND $y_2$) |
|---|---|---|---|---|
| 0 | 0 | 1 | 0 | 0 |
| 0 | 1 | 1 | 1 | 1 |
| 1 | 0 | 1 | 1 | 1 |
| 1 | 1 | 0 | 1 | 0 |

In [59]:
def xor_gate(X):
    y1 = nand_gate(X)  # perceptron, neuron
    y2 = or_gate(X)  
    Y = np.c_[y1, y2]  # layer
    z = and_gate6(Y)
    return z

In [60]:
xor_gate(X)

array([0, 1, 1, 0])