<a href="https://colab.research.google.com/github/JakeOh/202011_itw_bd21/blob/main/lab_ml/ml16_ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Artificial Neural Network(인공 신경망)**

# Imports

In [1]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris

import tensorflow as tf
from tensorflow import keras

In [2]:
tf.__version__  # Google Colab의 Tensorflow 버전 확인

'2.4.1'

In [3]:
keras.__version__  # Google Colab의 tensorflow.keras 버전 확인

'2.4.0'

# Iris Data

In [4]:
iris_data, iris_target = load_iris(return_X_y=True)

In [5]:
iris_data.shape, iris_target.shape

((150, 4), (150,))

In [6]:
iris_data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [7]:
np.unique(iris_target, return_counts=True)

(array([0, 1, 2]), array([50, 50, 50]))

샘플의 변수는 2개로 축소. 타겟(0:setosa, 1:non-setosa).

In [8]:
X = iris_data[:, -2:]
y = (iris_target != 0).astype(np.int32)

In [9]:
X[:5]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2]])

In [10]:
np.unique(y, return_counts=True)

(array([0, 1], dtype=int32), array([ 50, 100]))

## Single-layer 신경망

In [11]:
# 신경망 모델 생성 - 설계
model = keras.Sequential(layers=[keras.layers.Dense(units=1, activation='sigmoid', input_shape=(2,))], 
                         name='iris_single_layer')


*   `keras.Sequential` 클래스: 신경망 모델(input-hidden-output layer)
*   `keras.layers.Dense` 클래스: Dense 층(한개 이상의 unit(neuron)으로 이루어진 층)
    *   `units` 파라미터: dense layer가 갖는 유닛의 개수
    *   `activation` 파라미터: 활성화 함수 이름
    *   `input_shape` 파라미터: 한개의 유닛으로 입력되는 input data의 shape(튜플)
        *   신경망 모델이 찾아야 하는 파라미터(weights, bias)의 개수를 결정하기 위해서 필요.


In [12]:
# 생성된 신경망 모델 요약: layers, parameters
model.summary()

Model: "iris_single_layer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [13]:
# 신경망 모델 컴파일: optimizer, loss, metrics 등을 설정
#   optimizer: weight와 bias를 찾기위한 훈련 방법
#   loss: 비용 함수 (이름)
#   metrics: 성능 평가 지표(정확도, R2 score, RMSE 등)
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics='accuracy')

In [14]:
# 신경망 모델 훈련 - loss를 줄여주는, metric를 크게 만들어주는 weight와 bias를 찾는 과정.
model.fit(X, y, epochs=10)

Epoch 1/10
5/5 [==============================] - 3s 3ms/step - loss: 1.2617 - accuracy: 0.3247
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.9466 - accuracy: 0.3452
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.7469 - accuracy: 0.4951
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.6267 - accuracy: 0.6650
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.5243 - accuracy: 0.9560
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.4779 - accuracy: 0.9428
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.4595 - accuracy: 0.8767
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.4222 - accuracy: 0.8491
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.3988 - accuracy: 0.8089
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.4199 - accuracy: 0.7097
