<a href="https://colab.research.google.com/github/JakeOh/202011_itw_bd21/blob/main/lab_ml/ml16_ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Artificial Neural Network(인공 신경망)**

# Imports

In [1]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris

import tensorflow as tf
from tensorflow import keras

In [2]:
tf.__version__  # Google Colab의 Tensorflow 버전 확인

'2.4.1'

In [3]:
keras.__version__  # Google Colab의 tensorflow.keras 버전 확인

'2.4.0'

# Iris Data

In [4]:
iris_data, iris_target = load_iris(return_X_y=True)

In [5]:
iris_data.shape, iris_target.shape

((150, 4), (150,))

In [6]:
iris_data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [7]:
np.unique(iris_target, return_counts=True)

(array([0, 1, 2]), array([50, 50, 50]))

샘플의 변수는 2개로 축소. 타겟(0:setosa, 1:non-setosa).

In [8]:
X = iris_data[:, -2:]
y = (iris_target != 0).astype(np.int32)

In [9]:
X[:5]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2]])

In [10]:
np.unique(y, return_counts=True)

(array([0, 1], dtype=int32), array([ 50, 100]))

## Single-layer 신경망

In [11]:
# 신경망 모델 생성 - 설계
model = keras.Sequential(layers=[keras.layers.Dense(units=1, activation='sigmoid', input_shape=(2,))], 
                         name='iris_single_layer')


*   `keras.Sequential` 클래스: 신경망 모델(input-hidden-output layer)
*   `keras.layers.Dense` 클래스: Dense 층(한개 이상의 unit(neuron)으로 이루어진 층)
    *   `units` 파라미터: dense layer가 갖는 유닛의 개수
    *   `activation` 파라미터: 활성화 함수 이름
    *   `input_shape` 파라미터: 한개의 유닛으로 입력되는 input data의 shape(튜플)
        *   신경망 모델이 찾아야 하는 파라미터(weights, bias)의 개수를 결정하기 위해서 필요.


In [12]:
# 생성된 신경망 모델 요약: layers, parameters
model.summary()

Model: "iris_single_layer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [13]:
# 신경망 모델 컴파일: optimizer, loss, metrics 등을 설정
#   optimizer: weight와 bias를 찾기위한 훈련 방법
#   loss: 비용 함수 (이름)
#   metrics: 성능 평가 지표(정확도, R2 score, RMSE 등)
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics='accuracy')

In [14]:
# 신경망 모델 훈련: 훈련 데이터를 반복(epoch)해서 사용하면서,
# loss(손실)은 줄여주고 metric(성능 평가 점수)는 크게 만들어주는 파라미터들(weights, biases)를 찾는 과정.
model.fit(X, y, epochs=10)

Epoch 1/10
5/5 [==============================] - 3s 3ms/step - loss: 1.2617 - accuracy: 0.3247
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.9466 - accuracy: 0.3452
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.7469 - accuracy: 0.4951
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.6267 - accuracy: 0.6650
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.5243 - accuracy: 0.9560
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.4779 - accuracy: 0.9428
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.4595 - accuracy: 0.8767
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.4222 - accuracy: 0.8491
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.3988 - accuracy: 0.8089
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.4199 - accuracy: 0.7097


In [15]:
# 신경망 모델의 훈련이 끝난 후 파라미터들(weight, bias)
model.weights

[<tf.Variable 'dense/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[-0.20719218],
        [ 1.4455947 ]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.06050187], dtype=float32)>]

In [16]:
# 훈련된 모델 평가
model.evaluate(X, y)

5/5 [==============================] - 0s 2ms/step - loss: 0.4009 - accuracy: 0.7133


[0.40093016624450684, 0.7133333086967468]

In [17]:
# 훈련된 모델을 사용해서 예측
model.predict(X[[0, 50, 100]])
#> 이진 분류(binary class classification)에서 predict() 메서드는 양성 샘플(class=1)이 될 확률을 리턴.
#> (비교) scikit-learn 패키지의 머신 러닝 클래스들의 predict() 메서드는 예측 결과를 리턴함.

array([[0.5148835 ],
       [0.75222814],
       [0.91918576]], dtype=float32)

In [18]:
model.predict_proba(X[[0, 50, 100]])
#> deprecated: 미래에 없어질 예정인 기능.

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:425: UserWarning: `model.predict_proba()` is deprecated and will be removed after 2021-01-01. Please use `model.predict()` instead.
  warnings.warn('`model.predict_proba()` is deprecated and '


array([[0.5148835 ],
       [0.75222814],
       [0.91918576]], dtype=float32)

In [19]:
model.predict_classes(X[[0, 50, 100]])
#> deprecated: 미래에 없어질 예정인 기능.

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[1],
       [1],
       [1]], dtype=int32)

## DNN(Deep Neural Network)

Hidden layer(은닉층)이 한개 이상인 신경망 모델

In [27]:
# 모델 생성
model2 = keras.Sequential(name='iris_2_layers')

In [28]:
# Sequential 객체에 hidden layer를 추가
model2.add(keras.layers.Dense(units=10, activation='sigmoid', input_shape=(2,)))
# hidden layer 뒤에 output layer를 추가
model2.add(keras.layers.Dense(units=1, activation='sigmoid'))
# 첫번째 layer에서만 input_shape을 결정해 주면, 
# 두번째부터 연결되는 layer에서는 input_shape이 자동으로 계산되서 결정됨.

In [29]:
# 생성된 모델 요약
model2.summary()

Model: "iris_2_layers"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 10)                30        
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 11        
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [30]:
# 모델 컴파일: 최적화 알고리즘, 손실 함수, 평가 지표 등을 설정
model2.compile(optimizer='sgd', loss='binary_crossentropy', metrics='accuracy')

In [31]:
# 모델 훈련
model2.fit(X, y, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.7170 - accuracy: 0.6775
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.7208 - accuracy: 0.6528
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.7269 - accuracy: 0.6254
Epoch 4/10
5/5 [==============================] - 0s 4ms/step - loss: 0.7270 - accuracy: 0.6150
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.7122 - accuracy: 0.6437
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.7183 - accuracy: 0.6189
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.6975 - accuracy: 0.6649
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.7034 - accuracy: 0.6411
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.6965 - accuracy: 0.6541
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.6865 - accuracy: 0.6710


In [33]:
model2.weights
#> tf.Variable 클래스의 객체들을 저장하고 있는 리스트

[<tf.Variable 'dense_3/kernel:0' shape=(2, 10) dtype=float32, numpy=
 array([[ 0.12983035,  0.1786017 , -0.7036748 , -0.47096318, -0.22127809,
         -0.28041258, -0.3515727 ,  0.18599683, -0.7140175 ,  0.13760027],
        [-0.16443525, -0.16980414, -0.18544117,  0.22741961, -0.7120339 ,
          0.62472165,  0.03728396,  0.45265484, -0.70624876,  0.5159945 ]],
       dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(10,) dtype=float32, numpy=
 array([ 0.00056472,  0.00226899, -0.00851901, -0.00413155,  0.00525536,
         0.00225923,  0.00010678,  0.00155552, -0.00732538, -0.00057578],
       dtype=float32)>,
 <tf.Variable 'dense_4/kernel:0' shape=(10, 1) dtype=float32, numpy=
 array([[ 0.07390097],
        [ 0.2806682 ],
        [ 0.53257453],
        [ 0.5385329 ],
        [-0.49020708],
        [ 0.2471488 ],
        [-0.03128878],
        [-0.24562272],
        [ 0.4378515 ],
        [ 0.1934674 ]], dtype=float32)>,
 <tf.Variable 'dense_4/bias:0' shape=(1,) dtype=float32

In [34]:
model2.weights[0]  #> 입력 데이터들이 첫번째 layer로 입력될 때 곱해지게 될 weight 텐서

<tf.Variable 'dense_3/kernel:0' shape=(2, 10) dtype=float32, numpy=
array([[ 0.12983035,  0.1786017 , -0.7036748 , -0.47096318, -0.22127809,
        -0.28041258, -0.3515727 ,  0.18599683, -0.7140175 ,  0.13760027],
       [-0.16443525, -0.16980414, -0.18544117,  0.22741961, -0.7120339 ,
         0.62472165,  0.03728396,  0.45265484, -0.70624876,  0.5159945 ]],
      dtype=float32)>

In [35]:
model2.weights[1]  #> 입력 데이터들이 첫번째 layer로 입력될 때 더해지게 될 bias 텐서(tensor)

<tf.Variable 'dense_3/bias:0' shape=(10,) dtype=float32, numpy=
array([ 0.00056472,  0.00226899, -0.00851901, -0.00413155,  0.00525536,
        0.00225923,  0.00010678,  0.00155552, -0.00732538, -0.00057578],
      dtype=float32)>

In [36]:
# 평가
model2.evaluate(X, y)

5/5 [==============================] - 0s 3ms/step - loss: 0.6854 - accuracy: 0.6667


[0.6854140162467957, 0.6666666865348816]

In [37]:
# 예측
preds = model2.predict(X)
preds[[0, 1, 50, 51, 100, 101]]

array([[0.6324501 ],
       [0.6324501 ],
       [0.5856083 ],
       [0.58901244],
       [0.5912734 ],
       [0.5898272 ]], dtype=float32)

## iris 다중 클래스 분류

In [38]:
iris_data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [39]:
iris_target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [40]:
model = keras.Sequential()  # 신경망 생성

In [41]:
# 출력층 추가: 다중 클래스 분류인 경우 활성화 함수는 softmax를 사용.
model.add(keras.layers.Dense(units=3, activation='softmax', input_shape=(4,)))

In [42]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________
