<a href="https://colab.research.google.com/github/JakeOh/202011_itw_bd21/blob/main/lab_ml/ml18_cnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import convolve, correlate  # 합성곱(convolution) 연산

from sklearn.datasets import load_sample_image  # 예제 이미지 로드
from sklearn.model_selection import train_test_split

import tensorflow as tf
from tensorflow import keras

# Convolution(합성곱)

## 1차원 합성곱

In [3]:
x = np.arange(1, 5)
x

array([1, 2, 3, 4])

In [4]:
y = np.array([1, 2])
y

array([1, 2])

In [7]:
y_flipped = np.flip(y)
y_flipped  # 좌/우가 반전된 배열

array([2, 1])

In [5]:
convolve(x, y, mode='valid')
#> mode='valid': 출력 길이 = len(x) -len(y) + 1

array([ 4,  7, 10])

In [8]:
convolve(x, y, mode='same')
#> mode='same': 출력 길이 = len(x)
# 출력 배열의 길이가 원본 배열 x의 길이와 같아지도록 zero padding을 추가함.

array([ 1,  4,  7, 10])

In [9]:
convolve(x, y, mode='full')
#> mode='full': 출력 길이 = len(x) + len(y) - 1
# 원본 배열 x의 모든 원소가 동일한 횟수로 합성곱 연산에 기여할 수 있도록 zero padding을 추가함.

array([ 1,  4,  7, 10,  8])

## 2차원 합성곱

In [10]:
x2 = np.arange(1, 17).reshape((4, 4))
x2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
y2 = np.array([[0, 1], [2, 0]])
y2

array([[0, 1],
       [2, 0]])

In [12]:
np.flip(y2, axis=0)  # 상/하 반전

array([[2, 0],
       [0, 1]])

In [13]:
np.flip(y2, axis=1)  # 좌/우 반전

array([[1, 0],
       [0, 2]])

In [14]:
y2_flipped = np.flip(y2)  # 상/하/좌/우 반전
y2_flipped

array([[0, 2],
       [1, 0]])

In [15]:
convolve(x2, y2, mode='valid')

array([[ 9, 12, 15],
       [21, 24, 27],
       [33, 36, 39]])

In [16]:
convolve(x2, y2, mode='same')

array([[ 0,  1,  2,  3],
       [ 2,  9, 12, 15],
       [10, 21, 24, 27],
       [18, 33, 36, 39]])

In [17]:
convolve(x2, y2, mode='full')

array([[ 0,  1,  2,  3,  4],
       [ 2,  9, 12, 15,  8],
       [10, 21, 24, 27, 12],
       [18, 33, 36, 39, 16],
       [26, 28, 30, 32,  0]])

# Cross-correlation(교차상관)

In [18]:
x

array([1, 2, 3, 4])

In [19]:
y

array([1, 2])

In [21]:
correlate(x, y, mode='valid')

array([ 5,  8, 11])

In [22]:
correlate(x, y, mode='same')

array([ 2,  5,  8, 11])

In [23]:
correlate(x, y, mode='full')

array([ 2,  5,  8, 11,  4])

In [24]:
correlate(x2, y2, mode='valid')

array([[12, 15, 18],
       [24, 27, 30],
       [36, 39, 42]])

In [25]:
correlate(x2, y2, mode='same')

array([[ 0,  2,  4,  6],
       [ 1, 12, 15, 18],
       [ 5, 24, 27, 30],
       [ 9, 36, 39, 42]])

In [27]:
correlate(x2, y2, mode='full')

array([[ 0,  2,  4,  6,  8],
       [ 1, 12, 15, 18, 16],
       [ 5, 24, 27, 30, 24],
       [ 9, 36, 39, 42, 32],
       [13, 14, 15, 16,  0]])