<a href="https://colab.research.google.com/github/JakeOh/202011_itw_bd21/blob/main/lab_ml/ml18_cnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import convolve, correlate  # 합성곱(convolution) 연산

from sklearn.datasets import load_sample_image  # 예제 이미지 로드
from sklearn.model_selection import train_test_split

import tensorflow as tf
from tensorflow import keras

# Convolution(합성곱)

## 1차원 합성곱

In [3]:
x = np.arange(1, 5)
x

array([1, 2, 3, 4])

In [4]:
y = np.array([1, 2])
y

array([1, 2])

In [7]:
y_flipped = np.flip(y)
y_flipped  # 좌/우가 반전된 배열

array([2, 1])

In [5]:
convolve(x, y, mode='valid')
#> mode='valid': 출력 길이 = len(x) -len(y) + 1

array([ 4,  7, 10])

In [8]:
convolve(x, y, mode='same')
#> mode='same': 출력 길이 = len(x)
# 출력 배열의 길이가 원본 배열 x의 길이와 같아지도록 zero padding을 추가함.

array([ 1,  4,  7, 10])

In [9]:
convolve(x, y, mode='full')
#> mode='full': 출력 길이 = len(x) + len(y) - 1
# 원본 배열 x의 모든 원소가 동일한 횟수로 합성곱 연산에 기여할 수 있도록 zero padding을 추가함.

array([ 1,  4,  7, 10,  8])